name: CICD (Dev, Staging, Prod)
on:
  push:
    branches:
      - chore/test

jobs:
  staging-approval-gate:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: approved
        env: 
          ENV_NAME: Test
        run: echo "running"
    
  staging-deploy:
    needs: staging-approval-gate
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start deployment"
